# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- "*"
stages:
  - stage: Deploy
    jobs:
      - job: "deployARM"
        pool:
          vmimage: ubuntu-latest
        steps: 
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'testrun7-conn'
            subscriptionId: 'e3133bc0-5aab-42bd-b381-5860fe695537'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'testrun5'
            location: 'West US'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
            deploymentMode: 'Incremental'