# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- "*"
pool:
  vmImage: ubuntu-latest
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'testrun7-conn'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob service-properties update --account-name gborgwugclgpwelvyq --account-key cFjbbMdw3xa6LJRMZbm5Zk9rtbflO5oqVG9K9fgg4ILtEirzHxRIlI/8KA0jAGtk2I45DlDzsrXFcCXqrO1zwQ== --static-website --404-document 404.htm --index-document index.htm --verbose'